"""added ip-searchable lobbies

Revision ID: e34dee1b4c50
Revises: a1f4a09a1f90
Create Date: 2022-05-08 20:35:53.657539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34dee1b4c50'
down_revision = 'a1f4a09a1f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playsession', sa.Column('local_ip', sa.String(length=45), nullable=False))
    op.add_column('playsession', sa.Column('port', sa.Integer(), nullable=False))
    op.add_column('playsession', sa.Column('global_ip', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playsession', 'global_ip')
    op.drop_column('playsession', 'port')
    op.drop_column('playsession', 'local_ip')
    # ### end Alembic commands ###
